config/routes.rb
SoiafCharacterManager::Application.routes.draw do

   root 'welcome#index'

  resources :users
  resources :regions
  resources :houses
  resources :characters

  get "/session/new" => "session#new"
  post "/session" => "session#create"
  get "/logout" => "session#destroy"

  post "/characters/:id/export" => "characters#export"
  get "/oauth" => "characters#oauth"

end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  age             :integer
#  gender          :string(255)
#  house_id        :integer          default(1)
#  agility         :integer          default(2)
#  animal_handling :integer          default(2)
#  athletics       :integer          default(2)
#  awareness       :integer          default(2)
#  cunning         :integer          default(2)
#  deception       :integer          default(2)
#  endurance       :integer          default(2)
#  fighting        :integer          default(2)
#  healing         :integer          default(2)
#  language        :integer          default(2)
#  knowledge       :integer          default(2)
#  marksmanship    :integer          default(2)
#  persuasion      :integer          default(2)
#  status          :integer          default(2)
#  stealth         :integer          default(2)
#  survival        :integer          default(2)
#  thievery        :integer          default(2)
#  warfare         :integer          default(2)
#  will            :integer          default(2)
#  is_alive        :boolean          default(TRUE)
#  created_at      :datetime
#  updated_at      :datetime
#  user_id         :integer
#

class Character < ActiveRecord::Base
  belongs_to :house

  # need to establish validations

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = current_user.characters
  end

  def new
    # loads the current user's houses to make them available
    # in the drop down
    @houses = current_user.houses
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to("/")
    else
      render("/characters/new")
    end
  end

  def show
    @character = Character.find_by(id: params[:id])
    session[:char_id] = @character.id
  end

  def edit
    # loads the current user's houses to make them available
    # in the drop down
    @houses = current_user.houses
    @character = Character.find_by(id: params[:id])
  end

  def destroy
    character = Character.find_by({id: params[:id]})
    character.delete
    redirect_to("/characters")
  end

# pending a conversation with Phil, still not working
def oauth
  session[:auth_token] = GoogleOauth.oauth(params)
  puts "saving auth token #{session[:auth_token]}"
  redirect_to("/characters/#{session[:char_id]}")
end

# this allows users to export the current character
# to their Google Drive via OAuth
# OAuth2:  https://github.com/intridea/oauth2
# Google Drive Ruby Gem:  https://github.com/gimite/google-drive-ruby

# eventually should move this to the characters model
# or perhaps another model entirely, as we're going to
# want to be able to do this with houses too
def export
  @character = Character.find_by(id: params[:id])

  #creates client per instructions at:
  # http://gimite.net/doc/google-drive-ruby/GoogleDrive.html#method-c-login_with_oauth

  # client = OAuth2::Client.new(
  #   ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'],
  #   :site => "https://accounts.google.com",
  #   :token_url => "/o/oauth2/token",
  #   :authorize_url => "/o/oauth2/auth")
  # auth_url = client.auth_code.authorize_url(
  #   :redirect_uri => "http://localhost:3000/oauth",
  #       :scope =>
  #       "https://docs.google.com/feeds/ " +
  #       "https://docs.googleusercontent.com/")



  # redirect_to("https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/drive&redirect_uri=http://localhost:3000/oauth&response_type=code&client_id=#{ENV['GOOGLE_CLIENT_ID']}")

  # token_result = HTTParty.post("https://accounts.google.com/o/oauth2/token", :body => {:code => verification_code, :grant_type => "authorization_code"})

  # gets authorization code from Google
  # auth_code = params[:authenticity_token]
  # removes the = from the end of the code
  # auth_code.slice!("=")

  # should get the authorization token
  # auth_token = client.auth_code.get_token(
  #   auth_code, :redirect_uri => "http://localhost:3000/oauth")



  # create a session of Google Drive where it uses OAuth2
  drive_session = GoogleDrive.login_with_oauth(session[:auth_token])
  binding.pry

  # input a variable for naming the sheet
  # probably call it the character's name
  drive_session.create_spreadsheet("main_test")

  session_spreadsheet = drive_session.spreadsheet_by_title("main_test")

  session_worksheet = session_spreadsheet.worksheets[0]

  session_worksheet[1,1] = Time.now
  session_worksheet[2,1] = "Owner:"
  session_worksheet[2,2] = current_user.name

  session_worksheet[4,1] = "Name:"
  session_worksheet[4,2] = @character.name
  session_worksheet[4,3] = "Age:"
  session_worksheet[4,4] = @character.age
  session_worksheet[4,5] = "Gender:"
  session_worksheet[4,6] = @character.gender
  session_worksheet[4,7] = "House:"
  session_worksheet[4,8] = @character.house.name
  session_worksheet[6,1] = "Agility:"
  session_worksheet[6,2] = @character.agility
  session_worksheet[7,1] = "Animal Handling:"
  session_worksheet[7,2] = @character.animal_handling
  session_worksheet[8,1] = "Athletics:"
  session_worksheet[8,2] = @character.athletics
  session_worksheet[9,1] = "Awareness:"
  session_worksheet[9,2] = @character.awareness
  session_worksheet[10,1] = "Cunning:"
  session_worksheet[10,2] = @character.cunning
  session_worksheet[11,1] = "Deception:"
  session_worksheet[11,2] = @character.deception
  session_worksheet[12,1] = "Endurance:"
  session_worksheet[12,2] = @character.endurance
  session_worksheet[13,1] = "Fighting:"
  session_worksheet[13,2] = @character.fighting
  session_worksheet[14,1] = "Healing:"
  session_worksheet[14,2] = @character.healing
  session_worksheet[15,1] = "Language:"
  session_worksheet[15,2] = @character.language
  session_worksheet[6,4] = "Knowledge:"
  session_worksheet[6,5] = @character.knowledge
  session_worksheet[7,4] = "Marksmanship:"
  session_worksheet[7,5] = @character.marksmanship
  session_worksheet[8,4] = "Persuasion:"
  session_worksheet[8,5] = @character.persuasion
  session_worksheet[9,4] = "Status:"
  session_worksheet[9,5] = @character.status
  session_worksheet[10,4] = "Stealth:"
  session_worksheet[10,5] = @character.stealth
  session_worksheet[11,4] = "Survival:"
  session_worksheet[11,5] = @character.survival
  session_worksheet[12,4] = "Thievery:"
  session_worksheet[12,5] = @character.thievery
  session_worksheet[13,4] = "Warfare:"
  session_worksheet[13,5] = @character.warfare
  session_worksheet[14,4] = "Will:"
  session_worksheet[14,5] = @character.will

  if session_worksheet.save
    redirect_to("/characters")
  else
    puts "error error error"
  end

end

  private

  def character_params
    params.require(:character).permit(
      :name,
      :age,
      :gender,
      :house_id,
      :agility,
      :animial_handling,
      :athletics,
      :awareness,
      :cunning,
      :deception,
      :endurance,
      :fighting,
      :healing,
      :language,
      :knowledge,
      :marksmanship,
      :persuasion,
      :status,
      :stealth,
      :survival,
      :thievery,
      :warfare,
      :will,
      :is_alive,
      :user_id
      )
  end

end

app/views/characters/edit.html.erb
<a href="/characters">Go Back</a>

<%= form_for(@character) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <%= f.label(:age) %>
  <%= f.number_field(:age) %>
  <%= f.label(:gender) %>
  <%= f.text_field(:gender) %>
  <%= f.label(:house_id) %>
  <%= f.collection_select(:house_id, @houses, :id, :name) %>
  <%= f.label(:agility) %>
  <%= f.number_field(:agility) %>
  <%= f.label(:animal_handling) %>
  <%= f.number_field(:animal_handling) %>
  <%= f.label(:athletics) %>
  <%= f.number_field(:athletics) %>
  <%= f.label(:awareness) %>
  <%= f.number_field(:awareness) %>
  <%= f.label(:cunning) %>
  <%= f.number_field(:cunning) %>
  <%= f.label(:deception) %>
  <%= f.number_field(:deception) %>
  <%= f.label(:endurance) %>
  <%= f.number_field(:endurance) %>
  <%= f.label(:fighting) %>
  <%= f.number_field(:fighting) %>
  <%= f.label(:healing) %>
  <%= f.number_field(:healing) %>
  <%= f.label(:language) %>
  <%= f.number_field(:language) %>
  <%= f.label(:knowledge) %>
  <%= f.number_field(:knowledge) %>
  <%= f.label(:marksmanship) %>
  <%= f.number_field(:marksmanship) %>
  <%= f.label(:persuasion) %>
  <%= f.number_field(:persuasion) %>
  <%= f.label(:status) %>
  <%= f.number_field(:status) %>
  <%= f.label(:stealth) %>
  <%= f.number_field(:stealth) %>
  <%= f.label(:survival) %>
  <%= f.number_field(:survival) %>
  <%= f.label(:thievery) %>
  <%= f.number_field(:thievery) %>
  <%= f.label(:warfare) %>
  <%= f.number_field(:warfare) %>
  <%= f.label(:will) %>
  <%= f.number_field(:will) %>
  <%= f.label(:is_alive) %>
  <%= f.check_box(:is_alive) %>
  <%= f.submit %>
<% end %>

app/views/characters/index.html.erb
<h1>These are your characters</h1>

<a href="/">Home</a>

<% @characters.each do |character| %>
  <li>
    <%= link_to(character.name, action: :show, id: character.id) %>
    of <%= character.house.name %>
    <%= form_for(character, { :method => :delete }) do |f| %>
    <%= f.submit "Delete" %>
    <% end %>
  </li>
  <% end %>

app/views/characters/new.html.erb
<h1>Create a character</h1>

<%= form_for(@character) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <%= f.label(:age) %>
  <%= f.number_field(:age) %>
  <%= f.label(:gender) %>
  <%= f.text_field(:gender) %>
  <%= f.label(:house_id) %>
  <%= f.collection_select(:house_id, @houses, :id, :name) %>
  <%= f.label(:agility) %>
  <%= f.number_field(:agility) %>
  <%= f.label(:animal_handling) %>
  <%= f.number_field(:animal_handling) %>
  <%= f.label(:athletics) %>
  <%= f.number_field(:athletics) %>
  <%= f.label(:awareness) %>
  <%= f.number_field(:awareness) %>
  <%= f.label(:cunning) %>
  <%= f.number_field(:cunning) %>
  <%= f.label(:deception) %>
  <%= f.number_field(:deception) %>
  <%= f.label(:endurance) %>
  <%= f.number_field(:endurance) %>
  <%= f.label(:fighting) %>
  <%= f.number_field(:fighting) %>
  <%= f.label(:healing) %>
  <%= f.number_field(:healing) %>
  <%= f.label(:language) %>
  <%= f.number_field(:language) %>
  <%= f.label(:knowledge) %>
  <%= f.number_field(:knowledge) %>
  <%= f.label(:marksmanship) %>
  <%= f.number_field(:marksmanship) %>
  <%= f.label(:persuasion) %>
  <%= f.number_field(:persuasion) %>
  <%= f.label(:status) %>
  <%= f.number_field(:status) %>
  <%= f.label(:stealth) %>
  <%= f.number_field(:stealth) %>
  <%= f.label(:survival) %>
  <%= f.number_field(:survival) %>
  <%= f.label(:thievery) %>
  <%= f.number_field(:thievery) %>
  <%= f.label(:warfare) %>
  <%= f.number_field(:warfare) %>
  <%= f.label(:will) %>
  <%= f.number_field(:will) %>
  <%= f.label(:is_alive) %>
  <%= f.check_box(:is_alive) %>
  <%= f.hidden_field(:user_id, :value => current_user.id) %>
  <%= f.submit %>
<% end %>

app/views/characters/show.html.erb
<h1><%= @character.name %>'s Character Sheet</h1>
<a href="/characters">Go Back</a>

<%= link_to "edit_character", edit_character_path(@character) %>

<ul>Alive?:  <%=@character.is_alive%></ul>
<ul>Name: <%=@character.name%></ul>
<ul>House: <%=@character.house.name%></ul>
<ul>Age:  <%=@character.age%></ul>
<ul>Agility: <%=@character.agility%></ul>
<ul>Animal Handling: <%=@character.animal_handling%></ul>
<ul>Athletics: <%=@character.athletics%></ul>
<ul>Awareness: <%=@character.awareness%></ul>
<ul>Cunning:  <%=@character.cunning%></ul>
<ul>Deception:  <%=@character.deception%></ul>
<ul>Endurance:  <%=@character.endurance%></ul>
<ul>Fighting:  <%=@character.fighting%></ul>
<ul>Healing:  <%=@character.healing%></ul>
<ul>Language:  <%=@character.language%></ul>
<ul>Knowledge:  <%=@character.knowledge%></ul>
<ul>Marksmanship:  <%=@character.marksmanship%></ul>
<ul>Persuasion:  <%=@character.persuasion%></ul>
<ul>Status:  <%=@character.status%></ul>
<ul>Stealth:  <%=@character.stealth%></ul>
<ul>Survival:  <%=@character.survival%></ul>
<ul>Thievery:  <%=@character.thievery%></ul>
<ul>Warfare:  <%=@character.warfare%></ul>
<ul>Will:  <%=@character.will%></ul>

<a href="https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/drive&redirect_uri=http://localhost:3000/oauth&response_type=code&client_id=<%=ENV['GOOGLE_CLIENT_ID']%>">Sign in to Google</a>

<%= button_to "Export to Google", {:action => "export", :controller => "characters"} %>